name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_MENTION_ROLE_ID: ${{ secrets.DISCORD_MENTION_ROLE_ID }}
        run: |
          npx wrangler deploy src/index.ts \
            --name=smartwatchdog \
            --compatibility-date=2024-06-26 \
            --env=production \
            --var GOOGLE_CLIENT_EMAIL="$GOOGLE_CLIENT_EMAIL" \
            --var GOOGLE_PRIVATE_KEY="$GOOGLE_PRIVATE_KEY" \
            --var SPREADSHEET_ID="$SPREADSHEET_ID" \
            --var DISCORD_WEBHOOK_URL="$DISCORD_WEBHOOK_URL" \
            --var DISCORD_MENTION_ROLE_ID="$DISCORD_MENTION_ROLE_ID"