name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Generate wrangler.toml
        run: |
          cat <<EOF > wrangler.toml
          name = "smartwatchdog"
          main = "src/index.ts"
          compatibility_date = "2025-06-26"
          compatibility_flags = ["nodejs_compat"]
          kv_namespaces = [
            { binding = "STATUS_KV", id = "${{ secrets.STATUS_KV_ID }}" }
          ]
          [vars]
          GOOGLE_CLIENT_EMAIL = "${{ secrets.GOOGLE_CLIENT_EMAIL }}"
          GOOGLE_PRIVATE_KEY = "${{ secrets.GOOGLE_PRIVATE_KEY }}"
          SPREADSHEET_ID = "${{ secrets.SPREADSHEET_ID }}"
          DISCORD_WEBHOOK_URL = "${{ secrets.DISCORD_WEBHOOK_URL }}"
          DISCORD_MENTION_ROLE_ID = "${{ secrets.DISCORD_MENTION_ROLE_ID }}"
          RANGE = "${{ secrets.RANGE }}"
          [triggers]
          crons = ["*/10 * * * *"] 
          [observability.logs]
          enabled = true
          [build]
          command = "npm run build"
          [env.production.vars]
          PRODUCTION = "true"
          EOF
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
