name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Generate wrangler.toml
        run: |
          cat <<EOF > wrangler.toml
          name = "smartwatchdog"
          main = "src/index.ts"
          compatibility_date = "2025-06-26"
          compatibility_flags = ["nodejs_compat"]

          kv_namespaces = [
            { binding = "STATUS_KV", id = "${{ secrets.STATUS_KV_ID }}" }
          ]

          [triggers]
          crons = ["*/10 * * * *"] 

          [observability.logs]
          enabled = true

          [build]
          command = "npm run build"

          [env.production]
          kv_namespaces = [
            { binding = "STATUS_KV", id = "${{ secrets.STATUS_KV_ID }}" }
          ]
          EOF
      - name: Set secrets for Cloudflare Worker
        run: |
          npx wrangler secret put GOOGLE_CLIENT_EMAIL --env=production --non-interactive <<< "${{ secrets.GOOGLE_CLIENT_EMAIL }}"
          npx wrangler secret put GOOGLE_PRIVATE_KEY --env=production --non-interactive <<< "${{ secrets.GOOGLE_PRIVATE_KEY }}"
          npx wrangler secret put SPREADSHEET_ID --env=production --non-interactive <<< "${{ secrets.SPREADSHEET_ID }}"
          npx wrangler secret put DISCORD_WEBHOOK_URL --env=production --non-interactive <<< "${{ secrets.DISCORD_WEBHOOK_URL }}"
          npx wrangler secret put DISCORD_MENTION_ROLE_ID --env=production --non-interactive <<< "${{ secrets.DISCORD_MENTION_ROLE_ID }}"
          npx wrangler secret put RANGE --env=production --non-interactive <<< "${{ secrets.RANGE }}"
          npx wrangler secret put PRODUCTION --env=production --non-interactive <<< "${{ secrets.PRODUCTION }}"
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env=production
